/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author andon
 */
import BD.ConexionOracle;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import oracle.jdbc.OracleTypes;
import oracle.jdbc.OracleCallableStatement;
import java.sql.CallableStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

public class VentasFrame extends javax.swing.JFrame {

    /**
     * Creates new form VentasFrame
     */
    private DefaultTableModel modeloTabla;

    public VentasFrame() {
        initComponents();
        // Configurar el comportamiento de cierre para que solo cierre esta ventana
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        modeloTabla = (DefaultTableModel) tableVentas.getModel();
        actualizarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableVentas = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txfVentaID = new javax.swing.JTextField();
        txfFecha = new javax.swing.JTextField();
        txfCedulaID = new javax.swing.JTextField();
        txfTotal = new javax.swing.JTextField();
        btnObtenerVentas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        tableVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "VentaID", "Fecha", "CedulaID", "Total"
            }
        ));
        jScrollPane1.setViewportView(tableVentas);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setText("eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jLabel1.setText("VentaID");

        jLabel2.setText("Fecha");

        jLabel3.setText("CedulaID");

        jLabel4.setText("Total");

        btnObtenerVentas.setText("ObtenerVentas");
        btnObtenerVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObtenerVentasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txfVentaID, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txfFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txfCedulaID, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAgregar)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscar)
                                .addGap(18, 18, 18)
                                .addComponent(btnEditar)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminar)
                                .addGap(18, 18, 18)
                                .addComponent(btnObtenerVentas)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txfVentaID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txfFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txfCedulaID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnBuscar)
                    .addComponent(btnEditar)
                    .addComponent(btnEliminar)
                    .addComponent(btnObtenerVentas))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        try {
            // Obtener valores de los campos de texto
            Date fecha = Date.valueOf(txfFecha.getText()); // Convierte String a Date
            int cedulaID = Integer.parseInt(txfCedulaID.getText());
            double total = Double.parseDouble(txfTotal.getText());

            // Llamar al procedimiento almacenado para crear una nueva venta
            Connection conn = ConexionOracle.getConnection();
            CallableStatement cs = conn.prepareCall("{call CrearVenta(?, ?, ?)}");
            cs.setDate(1, fecha);
            cs.setInt(2, cedulaID);
            cs.setDouble(3, total);
            cs.execute();

            cs.close();
            conn.close();

            limpiarCampos();
            actualizarTabla();
            JOptionPane.showMessageDialog(this, "Venta agregada exitosamente.");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al agregar la venta: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            int ventaID;
            try {
                ventaID = Integer.parseInt(txfVentaID.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "ID de venta inválido. Asegúrese de ingresar un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            try (Connection conn = ConexionOracle.getConnection()) {
                String sql = "{call pkg_ventas.LeerVenta(?, ?, ?, ?)}";
                try (CallableStatement cs = conn.prepareCall(sql)) {
                    cs.setInt(1, ventaID);
                    cs.registerOutParameter(2, java.sql.Types.DATE);
                    cs.registerOutParameter(3, java.sql.Types.INTEGER);
                    cs.registerOutParameter(4, java.sql.Types.DOUBLE);
                    cs.execute();

                    limpiarTabla();
                    DefaultTableModel model = (DefaultTableModel) tableVentas.getModel();

                    Date fecha = cs.getDate(2);
                    if (fecha != null) {
                        model.addRow(new Object[]{
                            ventaID,
                            fecha,
                            cs.getInt(3),
                            cs.getDouble(4)
                        });
                    } else {
                        JOptionPane.showMessageDialog(this, "No se encontró la venta con el ID especificado.");
                    }
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al buscar la venta: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        try {
            int ventaID = Integer.parseInt(txfVentaID.getText());
            Date fecha = Date.valueOf(txfFecha.getText());
            int cedulaID = Integer.parseInt(txfCedulaID.getText());
            double total = Double.parseDouble(txfTotal.getText());

            Connection conn = ConexionOracle.getConnection();
            CallableStatement cs = conn.prepareCall("{call ActualizarVenta(?, ?, ?, ?)}");
            cs.setInt(1, ventaID);
            cs.setDate(2, fecha);
            cs.setInt(3, cedulaID);
            cs.setDouble(4, total);
            cs.execute();

            cs.close();
            conn.close();

            limpiarCampos();
            actualizarTabla();
            JOptionPane.showMessageDialog(this, "Venta actualizada exitosamente.");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al actualizar la venta: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        try {
            int ventaID = Integer.parseInt(txfVentaID.getText());

            Connection conn = ConexionOracle.getConnection();
            CallableStatement cs = conn.prepareCall("{call EliminarVenta(?)}");
            cs.setInt(1, ventaID);
            cs.execute();

            cs.close();
            conn.close();

            limpiarCampos();
            actualizarTabla();
            JOptionPane.showMessageDialog(this, "Venta eliminada exitosamente.");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al eliminar la venta: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnObtenerVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObtenerVentasActionPerformed
        Connection conn = null;
        CallableStatement cs = null;
        ResultSet rs = null;

        try {
            // Establecer la conexión con la base de datos
            conn = ConexionOracle.getConnection();

            // Preparar la llamada al procedimiento almacenado
            cs = conn.prepareCall("{call ObtenerVentas(?)}");

            // Registrar el parámetro de salida
            cs.registerOutParameter(1, OracleTypes.CURSOR);

            // Ejecutar el procedimiento
            cs.execute();

            // Obtener el cursor
            rs = (ResultSet) cs.getObject(1);

            // Limpiar la tabla
            limpiarTabla();

            // Llenar la tabla con los resultados
            DefaultTableModel model = (DefaultTableModel) tableVentas.getModel();
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("VentaID"),
                    rs.getDate("Fecha"),
                    rs.getInt("CedulaID"),
                    rs.getDouble("Total")
                });
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al obtener las ventas: " + ex.getMessage());
        } finally {
            // Cerrar recursos
            try {
                if (rs != null) {
                    rs.close();
                }
            } catch (SQLException e) {
                /* Ignorar */ }
            try {
                if (cs != null) {
                    cs.close();
                }
            } catch (SQLException e) {
                /* Ignorar */ }
            try {
                if (conn != null) {
                    conn.close();
                }
            } catch (SQLException e) {
                /* Ignorar */ }
        }
    }//GEN-LAST:event_btnObtenerVentasActionPerformed

    /**
     * @param args the command line arguments
     */
    private void limpiarTabla() {
        DefaultTableModel model = (DefaultTableModel) tableVentas.getModel();
        model.setRowCount(0);
    }

    private void limpiarCampos() {
        txfVentaID.setText("");
        txfFecha.setText("");
        txfCedulaID.setText("");
        txfTotal.setText("");
    }

    private void actualizarTabla() {
        try {
            Connection conn = ConexionOracle.getConnection();
            Statement stmt = conn.createStatement();

            String query = "SELECT * FROM Ventas";
            ResultSet rs = stmt.executeQuery(query);

            DefaultTableModel model = (DefaultTableModel) tableVentas.getModel();
            model.setRowCount(0);

            while (rs.next()) {
                int ventaID = rs.getInt("VentaID");
                Date fecha = rs.getDate("Fecha");
                int cedulaID = rs.getInt("CedulaID");
                double total = rs.getDouble("Total");

                model.addRow(new Object[]{ventaID, fecha, cedulaID, total});
            }

            rs.close();
            stmt.close();
            conn.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al actualizar la tabla: " + ex.getMessage());
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentasFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnObtenerVentas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableVentas;
    private javax.swing.JTextField txfCedulaID;
    private javax.swing.JTextField txfFecha;
    private javax.swing.JTextField txfTotal;
    private javax.swing.JTextField txfVentaID;
    // End of variables declaration//GEN-END:variables
}
